name: Windows Build Test

on:
  push:
    branches:
      - main  # যখন main ব্রাঞ্চে push হবে তখন রান করবে
  pull_request:
    branches:
      - main  # যখন কেউ PR করবে তখন রান করবে

jobs:
  build:
    runs-on: windows-latest  # Windows Runner ব্যবহার করা হচ্ছে

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # রিপোজিটরি ক্লোন করবে

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # নোডজে ইনস্টল করবে (কোটেশন বাদ দিন)

      - name: Install Dependencies
        run: npm install  # প্রজেক্ট ডিপেন্ডেন্সি ইনস্টল

      - name: Run Tests
        run: npm test  # টেস্ট রান করবে (যদি থাকে)

      - name: Build Project
        run: npm run build  # প্রজেক্ট বিল্ড করবে
