name: Multiple-Job Workflows

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest   # run this file in ubuntu server
        env:                     # set env or any secret file in git ripository > settings > Secret and Variables
            SECRETS_VAR: ${{ secrets.SECRET_VAR }}
            DEBUG: ${{ vars.DEBUG}}
        steps: 
            - name: Checkout code     # get all latest code that I change in my local environment
              uses: actions/checkout@v3
            - name: Print Hello World
              run: echo "Hello World"
            - name: Print the Secrets
              run: |                   # print multiple line
                echo "THe secret is: $SECRET_VAR"
                echo "THe variable is: $DEBUG"

    build:
        runs-on: ubuntu-latest
        needs: test          # first complete test job then run this build job. Its called dependency
        steps: 
            - name: Print test2
              run: echo "Here are the test2"

    deploy:
        runs-on: ubuntu-latest
        needs: [test, build]
        steps: 
            - name: Print deploy
              run: echo "Deploy complete"